on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy scipy matplotlib Pillow tqdm jpype1 mne
        pip install git+https://github.com/Imperial-MIND-lab/integrated-info-decomp.git
        
    - name: Run Tests
      run: |
        python -m unittest discover -s hyperit/tests

        
  paper:
    runs-on: ubuntu-latest
    name: Paper Draft
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build draft PDF
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss
          paper-path: hyperit/paper/paper.md
      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          name: joss_paper
          path: hyperit/paper/paper.pdf
